data_dir: data
download:
  connections: 4
  temp_dir: /tmp/pmxt_ingestion
start_date: 2026-04-27T06
end_date: 2026-04-27T10
markets:
- asset: btc
  duration: 5m
- asset: eth
  duration: 5m
- asset: sol
  duration: 5m
- asset: xrp
  duration: 5m
